version: '2.3'
services:
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    command: /bin/builder.bash deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    environment:
      - REPO_TOKEN=${REPO_TOKEN}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
